name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Starting tests
        run: |
          echo "Starting tests!"
      - name: client - install dependencies
        run: cd client && npm install
      - name: server - install dependencies
        run: cd server && npm install