name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Starting tests
        run: |
          echo "Starting tests"
          cd server && touch .env
          echo TEST_MONGODB_URI="$TEST_MONGODB_URI" >> .env
          echo SECRET="$SECRET" >> .env
          echo PORT="$PORT" >> .env
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
          PORT: ${{secrets.PORT}}
      - name: client - install dependencies
        run: cd client && npm install
      - name: server - install dependencies
        run: cd server && npm install
      - name: check linting
        run: cd server && npm run lint && npm run lint:client
      - name: run unit tests
        run: cd server && npm run test
      - name: run build
        run: cd server && npm run build
      - name: start testing server
        run: cd server && npm run start:test & npx wait-on http://localhost:3003
      - name: run e2e-tests
        run: cd server && npm run test:e2e
      - name: deployment
        id: herokuDeployment
        if: ${{ (github.event_name == 'push') && !(contains(join(toJson(github.event.commits.*.message)),'#skip')) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fso-osa11-blogger"
          heroku_email: ${{secrets.HEROKU_API_USER}}
          healthcheck: "https://fso-osa11-blogger.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          delay: 5
      - name: Bump version and push tag
        if: ${{ (github.event_name == 'push') && !(contains(join(toJson(github.event.commits.*.message)),'#skip')) }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          
